AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Gateway triggering a Lambda function

Globals:
  Function:
    Timeout: 10

Resources:
  SAMApiGatewayLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SAMApiGatewayLambda
      CodeUri: ./SAMApiGatewayLambda/bin/Debug/netcoreapp2.1/publish
      Handler: SAMApiGatewayLambda::SAMApiGatewayLambda.SAMApiGatewayHandler::Handle
      Runtime: dotnetcore2.1
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        SAMApiGatewayLambda:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  SAMApiGatewayLambdaURL:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/SAMApiGatewayLambda/"

  SAMApiGatewayLambdaArn:
    Value: !GetAtt SAMApiGatewayLambdaFunction.Arn