AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple API Gateway triggering a Lambda function

Resources:
  SAMApiGatewayLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sam-api-gateway-lambda
      CodeUri: ./SAMApiGatewayLambda/bin/Debug/netcoreapp2.1/publish
      Handler: SAMApiGatewayLambda::SAMApiGatewayLambda.SAMApiGatewayHandler::Handle
      Runtime: dotnetcore2.1
      Events:
        SAMApiGatewayLambda:
          Type: Api
          Properties:
            Path: /
            Method: get

Outputs:
  SAMApiGatewayLambdaURL:
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  SAMApiGatewayLambdaArn:
    Value: !GetAtt "SAMApiGatewayLambdaFunction.Arn"
